# Generated by Django 3.2.5 on 2021-07-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
